# Streamlit Secrets Configuration
# WARNING: Do not commit this file to version control!

# API Keys
GROQ_API_KEY = "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"  # Get your key from https://console.groq.com

# You can add other sections for different types of secrets
[database]
# Add database credentials here if needed
# username = ""
# password = ""

[api_credentials]
# Add other API credentials here if needed
